# Generated by Django 5.2.6 on 2025-12-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='funder',
            new_name='organization',
        ),
    ]
