# Generated by Django 5.0 on 2026-02-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_rename_funder_scholarship_organization'),
        ('users', '0004_studentprofile_karma_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='finder_karma_awarded',
            field=models.IntegerField(default=0, help_text='Karma points awarded to finder'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='found_by_student',
            field=models.ForeignKey(blank=True, help_text='Student who submitted this scholarship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_scholarships', to='users.studentprofile'),
        ),
    ]
