# Generated by Django 5.0 on 2026-02-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_scholarship_finder_karma_awarded_and_more'),
        ('users', '0004_studentprofile_karma_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='about',
            field=models.TextField(default='', help_text='Rich description of the scholarship mission and impact'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='award_per_student',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount per winner (used for FIXED distribution)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='custom_essay_question',
            field=models.TextField(blank=True, default='', help_text='Optional essay prompt shown to students during application'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='demographic_focus',
            field=models.JSONField(blank=True, default=list, help_text="List of targeted groups e.g. ['women', 'tier2_city', 'sc_st']"),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='disbursement_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank Transfer (Razorpay Route)'), ('VOUCHER', 'Educational Vouchers Only')], default='BANK_TRANSFER', max_length=15),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='distribution_logic',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount per Winner'), ('DYNAMIC', 'Dynamic — Proportional to Need')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='escrow_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('FUNDED', 'Funded (In Escrow)'), ('DISBURSED', 'Disbursed to Students'), ('REFUNDED', 'Refunded to Organization')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo shown on the student card', null=True, upload_to='scholarship_logos/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_family_income',
            field=models.IntegerField(blank=True, help_text='Maximum annual family income in ₹ (leave blank for no restriction)', null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='max_winners',
            field=models.IntegerField(default=1, help_text='Maximum number of students to award'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_academic_score',
            field=models.FloatField(blank=True, help_text='Minimum % or CGPA required in the previous year', null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_karma_required',
            field=models.IntegerField(default=0, help_text='Student must have at least this many karma points to apply'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='streams',
            field=models.CharField(blank=True, default='', help_text='Comma-separated streams (e.g. B.Tech, MBBS, Arts)', max_length=500),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='target_education_level',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'High School / 10th-12th'), ('DIPLOMA', 'Diploma / ITI'), ('UNDERGRAD', 'Undergraduate (B.Tech, B.Sc, BA, etc.)'), ('POSTGRAD', 'Postgraduate (M.Tech, MBA, M.Sc, etc.)'), ('PHD', 'Ph.D / Doctoral'), ('ANY', 'Any Level')], default='ANY', max_length=20),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total funds the organization will deposit into escrow', max_digits=12),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='verification_strictness',
            field=models.CharField(choices=[('STANDARD', 'Standard — Manual Upload + AI Check'), ('STRICT', 'Strict — DigiLocker / Govt API Verification')], default='STANDARD', max_length=10),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='comparison_operator',
            field=models.CharField(choices=[('GT', '>'), ('LT', '<'), ('GTE', '>='), ('LTE', '<='), ('EQ', '='), ('IN', 'IN')], default='GT', max_length=3),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteria',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='scholarships.scholarship'),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='scholarships.scholarship'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='award_amount',
            field=models.CharField(blank=True, default='', help_text='Legacy text display field (auto-set from total_budget)', max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateTimeField(help_text='Exact date and time when applications close'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='details',
            field=models.TextField(blank=True, default='', help_text="Legacy details field — use 'about' for new scholarships"),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='finder_karma_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='found_by_student',
            field=models.ForeignKey(blank=True, help_text='Student who submitted this scholarship via finder bounty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_scholarships', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Visible to students only when funded + active'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='users.organizationprofile'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='ScholarshipEscrowLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_locked', models.DecimalField(decimal_places=2, help_text='Total amount held in escrow (deposited by org)', max_digits=12)),
                ('amount_released', models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid out to winning students', max_digits=12)),
                ('funded_at', models.DateTimeField(blank=True, help_text='When payment was confirmed', null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, help_text='When all payouts were triggered', null=True)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('scholarship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_ledger', to='scholarships.scholarship')),
            ],
        ),
    ]
