# Generated by Django 5.0 on 2026-02-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_scholarship_about_scholarship_award_per_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['-last_updated']},
        ),
    ]
