# Generated by Django 5.0 on 2026-02-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        ('scholarships', '0007_remove_scholarship_about_and_more'),
        ('users', '0005_add_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='applications_closed',
            field=models.BooleanField(default=False, help_text='Org can manually close applications before deadline'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when org manually closed applications', null=True),
        ),
        migrations.CreateModel(
            name='FeesVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_receipt_file', models.FileField(upload_to='otr/fees_receipts/%Y/%m/', verbose_name='College Fees Receipt')),
                ('total_annual_fees', models.PositiveIntegerField(blank=True, help_text='Fees amount extracted by Gemini from the receipt', null=True, verbose_name='Total Annual Fees (Rs.)')),
                ('extracted_college_name', models.CharField(blank=True, help_text='College/institution name as extracted by Gemini', max_length=255)),
                ('extracted_student_name', models.CharField(blank=True, help_text='Student name as extracted by Gemini', max_length=150)),
                ('extracted_academic_year', models.CharField(blank=True, help_text='Academic year extracted from the receipt (e.g. 2023-24)', max_length=20)),
                ('college_match', models.BooleanField(default=False, help_text="True when receipt college name matches the student's registered institution")),
                ('gemini_verified', models.BooleanField(default=False, help_text='True when Gemini successfully extracted and matched receipt data')),
                ('raw_gemini_response', models.TextField(blank=True, help_text='Raw JSON response from Gemini for audit purposes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees_verification', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Fees Verification',
            },
        ),
        migrations.CreateModel(
            name='MarksheetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksheet_file', models.FileField(upload_to='otr/marksheets/%Y/%m/', verbose_name='Last Semester Marksheet')),
                ('last_sem_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage extracted by Gemini from the marksheet', max_digits=5, null=True, verbose_name='Last Semester Marks (%)')),
                ('extracted_institution', models.CharField(blank=True, help_text='Institution name as extracted by Gemini', max_length=255)),
                ('extracted_semester', models.CharField(blank=True, help_text='Semester / year as extracted by Gemini', max_length=50)),
                ('extracted_student_name', models.CharField(blank=True, help_text='Student name as extracted by Gemini', max_length=150)),
                ('gemini_verified', models.BooleanField(default=False, help_text='True when Gemini extraction matched the student profile')),
                ('raw_gemini_response', models.TextField(blank=True, help_text='Raw JSON response from Gemini for audit purposes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marksheet_verification', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Marksheet Verification',
            },
        ),
        migrations.CreateModel(
            name='ScholarshipAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('merit_rank', models.PositiveIntegerField(default=0)),
                ('marks_at_award', models.DecimalField(blank=True, decimal_places=2, help_text='last_sem_marks at the time of award', max_digits=5, null=True)),
                ('fees_at_award', models.PositiveIntegerField(blank=True, help_text='total_annual_fees at the time of award', null=True)),
                ('prior_received', models.PositiveIntegerField(default=0, help_text='Total scholarship Rs. received before this award (for need score)')),
                ('amount_awarded', models.PositiveIntegerField(default=0, verbose_name='Amount Awarded (Rs.)')),
                ('transfer_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Organisation'), ('PROCESSING', 'Bank Transfer Initiated'), ('DONE', 'Transfer Completed'), ('FAILED', 'Transfer Failed — Retry Needed')], default='PENDING', max_length=12)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100)),
                ('transfer_ref', models.CharField(blank=True, help_text='Razorpay payout reference or UTR number', max_length=255)),
                ('transfer_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='applications.application')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.studentprofile')),
            ],
            options={
                'verbose_name': 'Scholarship Award',
                'ordering': ['merit_rank'],
            },
        ),
    ]
