# Generated by Django 5.0 on 2026-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_alter_scholarship_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateTimeField(verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(verbose_name='About the Scholarship (HTML allowed)'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='disbursement_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Direct Bank Transfer (Razorpay Route)'), ('VOUCHER', 'Educational Vouchers Only')], default='BANK_TRANSFER', max_length=20, verbose_name='Disbursement Method'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='scholarship_logos/', verbose_name='Organization Logo'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='max_family_income',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum annual family income in INR (e.g. 800000 for ₹8 lakh)', null=True, verbose_name='Max Family Annual Income (₹)'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='organization',
            field=models.CharField(blank=True, help_text='[Legacy] Organization name as string. Use org_profile FK instead.', max_length=255),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Scholarship Title'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='total_budget',
            field=models.PositiveIntegerField(help_text='Full amount the organization deposits into escrow (INR)', verbose_name='Total Budget (₹)'),
        ),
    ]
