# Generated by Django 5.0 on 2026-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0010_alter_scholarship_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='total_budget',
            field=models.PositiveIntegerField(blank=True, help_text='Full amount the organization deposits into escrow (INR)', null=True, verbose_name='Total Budget (₹)'),
        ),
    ]
