# Generated by Django 5.0 on 2026-03-01 02:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0011_add_nullable_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID embedded in QR code for public verification', unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True, help_text='Set to False to revoke this certificate (e.g. fraud detected)')),
                ('certificate_image', models.ImageField(blank=True, upload_to='certificates/', verbose_name='Certificate Image (PNG)')),
                ('qr_code', models.ImageField(blank=True, upload_to='certificates/qr/', verbose_name='QR Code Image')),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='scholarships.scholarshipaward')),
            ],
            options={
                'verbose_name': 'Scholarship Certificate',
                'verbose_name_plural': 'Scholarship Certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
