# Generated by Django 5.2.6 on 2025-12-11 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organization_name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(max_length=150)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=2000)),
                ('is_verified_funder', models.BooleanField(default=False, help_text='Verified by platform administration')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_organization',
            field=models.BooleanField(default=False),
        ),
    ]
