# Generated by Django 5.0 on 2026-02-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organizationprofile_user_is_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otr_completed',
            field=models.BooleanField(default=False, help_text='Has student completed OTR?'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='otr_step',
            field=models.IntegerField(default=1, help_text='Current OTR step (1-7)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_completion',
            field=models.IntegerField(default=0, help_text='Profile completion percentage'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='current_year',
            field=models.IntegerField(blank=True, help_text='Current year of study', null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='degree_level',
            field=models.CharField(choices=[('10th', '10th Grade'), ('12th', '12th Grade'), ('Diploma', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PhD', 'Doctorate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='last_exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage or CGPA', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='stream',
            field=models.CharField(blank=True, help_text='E.g., Science, Commerce, Engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='caste_category',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Person with Disability'),
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('income_cert', 'Income Certificate'), ('caste_cert', 'Caste Certificate'), ('disability_cert', 'Disability Certificate'), ('marksheet_10', '10th Marksheet'), ('marksheet_12', '12th Marksheet'), ('current_marksheet', 'Current Semester/Year Marksheet'), ('bank_passbook', 'Bank Passbook'), ('photo', 'Passport Photo'), ('other', 'Other Document')], max_length=50)),
                ('file', models.FileField(upload_to='student_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'document_type')},
            },
        ),
    ]
