# Generated by Django 5.0 on 2026-02-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='karma_rank',
            field=models.IntegerField(blank=True, help_text='Rank on leaderboard', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_karma_points',
            field=models.IntegerField(default=0, help_text='Total karma points balance'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verified_scholar_badge',
            field=models.BooleanField(default=False, help_text='Has purchased verified scholar badge'),
        ),
    ]
