# Generated by Django 5.2.6 on 2025-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('MOD_VERIFIED', 'Moderator Verified'), ('SUBMITTED', 'Submitted to Funder'), ('APPROVED', 'Approved by Funder'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('application_link', models.URLField(blank=True, max_length=2000)),
                ('last_action_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='application_docs/')),
                ('ai_verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('AI_OK', 'AI Verified OK'), ('AI_FLAG', 'AI Flagged Issue'), ('MOD_OK', 'Moderator Verified OK')], default='PENDING', max_length=10)),
                ('moderator_verified', models.BooleanField(default=False)),
                ('moderator_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
