services:
  - type: web
    name: scholar-match
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn scholar_match.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
