services:
  - type: web
    name: scholar-match
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: "./build.sh"
    startCommand: "gunicorn scholar_match.wsgi:application --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"
