# Generated by Django 5.2.6 on 2025-12-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('moderator_panel', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatoractivitylog',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.moderatorprofile'),
        ),
        migrations.AddField(
            model_name='moderatoractivitylog',
            name='target_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.application'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.moderatorprofile'),
        ),
    ]
