# Generated by Django 5.2.6 on 2025-12-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('ELIGIBILITY', 'Eligibility Check'), ('DOCUMENT_OCR', 'Document OCR/Validation')], max_length=50)),
                ('input_data', models.JSONField(default=dict)),
                ('result_json', models.JSONField(default=dict)),
                ('is_success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
