# Generated by Django 5.0 on 2026-02-08 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0003_scholarship_finder_karma_awarded_and_more'),
        ('users', '0004_studentprofile_karma_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.CharField(max_length=200)),
                ('karma_cost', models.IntegerField(help_text='Points required to redeem')),
                ('reward_type', models.CharField(choices=[('VOUCHER', 'Voucher (Zomato, Lenskart, etc.)'), ('BADGE', 'Profile Badge'), ('PRIORITY_SERVICE', 'Priority Service')], max_length=20)),
                ('description', models.TextField()),
                ('stock_quantity', models.IntegerField(blank=True, help_text='Leave blank for unlimited stock', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active and available for redemption')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['karma_cost'],
            },
        ),
        migrations.CreateModel(
            name='KarmaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for earning, negative for spending')),
                ('transaction_type', models.CharField(choices=[('FINDER_BOUNTY', 'Finder Bounty - Scholarship Submission'), ('OTR_COMPLETE', 'OTR Completion Bonus'), ('REDEEM_REWARD', 'Reward Redemption'), ('PENALTY_FAKE', 'Penalty - Fake Submission'), ('ADMIN_ADJUST', 'Admin Manual Adjustment')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_scholarship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_transactions', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma_spent', models.IntegerField()),
                ('redemption_code', models.CharField(help_text='Unique code for reward fulfillment', max_length=16, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='karma.karmareward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='users.studentprofile')),
            ],
            options={
                'verbose_name_plural': 'Redemption Histories',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=100)),
                ('website_url', models.URLField(max_length=2000)),
                ('proof_document', models.FileField(help_text='Upload proof (screenshot, PDF, etc.)', upload_to='scholarship_submissions/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('karma_awarded', models.IntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, help_text='Moderator notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='users.moderatorprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_submissions', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
